const ads = [
  {
    id: 1,
    trader: "CryptoWhale",
    type: "buy",
    asset: "USDT",
    fiat: "PKR",
    price: 285.50,  // ✅ Sahi
    amount: "500 - 50,000",
    payment: ["Bank Transfer", "JazzCash", "EasyPaisa"],
    completion: 98,
    verified: true,
    online: true,
  },
  {
    id: 2,
    trader: "BitcoinKing",
    type: "sell",
    asset: "USDT",
    fiat: "PKR",
    price: 284.75,  // ✅ Sahi
    amount: "200 - 25,000",
    payment: ["Bank Transfer", "EasyPaisa"],
    completion: 95,
    verified: true,
    online: true,
  },
  {
    id: 3,
    trader: "CryptoTrader",
    type: "buy",
    asset: "BTC",
    fiat: "PKR",
    price: 18500,  // ✅ Comma HATAYA!
    amount: "0.01 - 1.0",
    payment: ["Bank Transfer", "JazzCash"],
    completion: 100,
    verified: false,
    online: false,
  },
  {
    id: 4,
    trader: "P2PKing",
    type: "sell",
    asset: "USDT",
    fiat: "PKR",
    price: 285.00,  // ✅ Sahi
    amount: "1,000 - 100,000",
    payment: ["Bank Transfer", "JazzCash", "EasyPaisa", "Meezan"],
    completion: 92,
    verified: true,
    online: true,
  },
  {
    id: 5,
    trader: "HODLer",
    type: "buy",
    asset: "ETH",
    fiat: "PKR",
    price: 850,  // ✅ Sahi
    amount: "0.5 - 10",
    payment: ["Bank Transfer"],
    completion: 88,
    verified: true,
    online: false,
  },
];
